import card1 from "@/assets/images/card1.jpg";
import card2 from "@/assets/images/card2.jpg";
import card3 from "@/assets/images/card3.jpg";
import card4 from "@/assets/images/card4.jpg";
import card5 from "@/assets/images/card5.jpg";
import card6 from "@/assets/images/card6.jpg";
export const ConcertDemoApiData = () => {
  return [
    {
      idx: 0,
      id: "1",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_1",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "electronic",
      locationTagName: "北部",
    },
    {
      idx: 1,
      id: "2",
      date: "2025/07/10",
      title: "周杰倫《嘉年華》巡迴演唱會_2",
      image: card2,
      location: "台北小巨蛋",
      link: "/",
      category: "hip-hop/rap",
      locationTagName: "北部",
    },
    {
      idx: 2,
      id: "3",
      date: "2025/08/17",
      title: "BTS (Beyond the Scene》世界巡迴_3",
      image: card3,
      location: "新北大都會公園",
      link: "/",
      category: "electronic",
      locationTagName: "南部",
    },
    {
      idx: 3,
      id: "4",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_4",
      image: card4,
      location: "台北小巨蛋",
      link: "/",
      category: "rock",
      locationTagName: "中部",
    },
    {
      idx: 4,
      id: "5",
      date: "2025/09/10",
      title: "周杰倫《嘉年華》巡迴演唱會_5",
      image: card5,
      location: "台北小巨蛋",
      link: "/",
      category: "jazz/blues",
      locationTagName: "南部",
    },
    {
      idx: 5,
      id: "6",
      date: "2025/08/17",
      title: "BTS (Beyond the Scene》世界巡迴_6",
      image: card6,
      location: "新北大都會公園",
      link: "/",
      category: "classical/symphony",
      locationTagName: "南部",
    },
    {
      idx: 6,
      id: "7",
      date: "2025/09/15",
      title: "五月天《回到未來》世界巡迴_7  ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "hip-hop/rap",
      locationTagName: "北部",
    },
    {
      idx: 7,
      id: "8",
      date: "2025/08/15",
      title: "五月天《回到未來》世界巡迴_8",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "hip-hop/rap",
      locationTagName: "離島",
    },
    {
      idx: 8,
      id: "9",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_9  ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "others",
      locationTagName: "北部",
    },
    {
      idx: 9,
      id: "10",
      date: "2025/07/15",
      title: "五月天《回到未來》世界巡迴_10 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "rock",
      locationTagName: "中部",
    },
    {
      idx: 10,
      id: "11",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_11 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "jazz/blues",
      locationTagName: "南部",
    },
    {
      idx: 11,
      id: "12",
      date: "2025/07/10",
      title: "周杰倫《嘉年華》巡迴演唱會_12",
      image: card2,
      location: "台北小巨蛋",
      link: "/",
      category: "classical/symphony",
      locationTagName: "南部",
    },
    {
      idx: 12,
      id: "13",
      date: "2025/09/17",
      title: "BTS (Beyond the Scene》世界巡迴_13",
      image: card3,
      location: "新北大都會公園",
      link: "/",
      category: "electronic",
      locationTagName: "中部",
    },
    {
      idx: 13,
      id: "14",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_14",
      image: card4,
      location: "台北小巨蛋",
      link: "/",
      category: "rock",
      locationTagName: "海外",
    },
    {
      idx: 14,
      id: "15",
      date: "2025/07/10",
      title: "周杰倫《嘉年華》巡迴演唱會_15",
      image: card5,
      location: "台北小巨蛋",
      link: "/",
      category: "pop",
      locationTagName: "北部",
    },
    {
      idx: 15,
      id: "16",
      date: "2025/08/17",
      title: "BTS (Beyond the Scene》世界巡迴_16",
      image: card6,
      location: "新北大都會公園",
      link: "/",
      category: "classical/symphony",
      locationTagName: "南部",
    },
    {
      idx: 16,
      id: "17",
      date: "2025/05/15",
      title: "五月天《回到未來》世界巡迴_17 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "hip-hop/rap",
      locationTagName: "中部",
    },
    {
      idx: 17,
      id: "18",
      date: "2025/06/15",
      title: "五月天《回到未來》世界巡迴_18 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "hip-hop/rap",
      locationTagName: "南部",
    },
    {
      idx: 18,
      id: "19",
      date: "2025/07/15",
      title: "五月天《回到未來》世界巡迴_19 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "others",
      locationTagName: "離島",
    },
    {
      idx: 19,
      id: "20",
      date: "2025/08/15",
      title: "五月天《回到未來》世界巡迴_20 ",
      image: card1,
      location: "台北小巨蛋",
      link: "/",
      category: "electronic",
      locationTagName: "海外",
    },
  ];
};
